# Generated by Django 3.2 on 2022-06-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='message.store', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='message.store', verbose_name='店舗'),
        ),
    ]
