# Generated by Django 3.2 on 2022-06-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(),
        ),
    ]
