# Generated by Django 3.2 on 2022-06-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220627_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.store', verbose_name='店舗'),
        ),
    ]
