# Generated by Django 3.2 on 2022-06-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_remove_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
