# Generated by Django 4.0.5 on 2022-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dest_ID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='indivisual_ID',
            field=models.PositiveIntegerField(),
        ),
    ]
