# Generated by Django 4.0.5 on 2022-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_rename_start_data_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('confirmed_flag', models.IntegerField()),
            ],
        ),
    ]
