# Generated by Django 4.0.5 on 2022-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_message_dest_id_alter_message_indivisual_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('confirmed_flag', models.IntegerField()),
                ('store_id', models.CharField(max_length=20)),
            ],
        ),
    ]
