# Generated by Django 4.0.5 on 2022-07-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_shiftdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='dest_ID',
            new_name='dest_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='indivisual_ID',
            new_name='indivisual_id',
        ),
    ]
